### ISSUE TITLE
The API not showing data in Grafana Dashboard

### ISSUE THREAD

**Issue by moatazeldebsy** [DamienBitrise/bitrise-grafana-api#2]
We are following the steps in the `README` file but the data not displayed on the dashboard 

<img width="853" alt="Screenshot 2020-09-07 at 21 24 28" src="https://user-images.githubusercontent.com/45570191/92413513-c8fe2d00-f150-11ea-9765-0dd6459f77ca.png">
<img width="1673" alt="Screenshot 2020-09-07 at 21 25 32" src="https://user-images.githubusercontent.com/45570191/92413520-cc91b400-f150-11ea-8ed4-b6dea509abae.png">

when I tried the API using CURL it's working normally for example: 

`curl -H 'Authorization: API_KEY' https://api.bitrise.io/v0.1/builds`

also with the Grafana Dashboard, I tried to use in the URL https://api.bitrise.io/v0.1/builds or the URL from Repl.it but the same

<img width="988" alt="Screenshot 2020-09-07 at 21 29 20" src="https://user-images.githubusercontent.com/45570191/92413630-3d38d080-f151-11ea-9e1e-d8f6715508ee.png">

and sometimes we got this internal server error

<img width="562" alt="Screenshot 2020-09-07 at 21 36 48" src="https://user-images.githubusercontent.com/45570191/92413854-424a4f80-f152-11ea-9d4f-18232456911b.png">
<img width="824" alt="Screenshot 2020-09-07 at 21 35 02" src="https://user-images.githubusercontent.com/45570191/92413888-6148e180-f152-11ea-9876-7ddc81e408e0.png">

**Comment by DamienBitrise** [comment]
Make sure to deselect and reselect the data sources in the dashboard panels 

See: https://github.com/DamienBitrise/bitrise-grafana-api#reselect-the-datasources

**Comment by moatazeldebsy** [comment]
I did a lot of times bu no change

**Comment by DamienBitrise** [comment]
Without the error from the server it is hard to say what might be wrong

![image](https://user-images.githubusercontent.com/60897705/92645819-48e3de80-f29a-11ea-9846-7d0928518e6b.png)

What exactly is undefined?

**Comment by DamienBitrise** [comment]
You can also open the Query Inspector to verify your API is working

![image](https://user-images.githubusercontent.com/60897705/92646237-f9ea7900-f29a-11ea-9246-5f5e94a46cce.png)

You should see something like this if your API is working

![image](https://user-images.githubusercontent.com/60897705/92646268-08389500-f29b-11ea-8933-327c8f583d12.png)
