### ISSUE TITLE
Why repl.co url hardcoded in node code?

### ISSUE THREAD

**Issue by azhurbilo** [DamienBitrise/bitrise-grafana-api#3]
```
function keepAlive(){
  fetch('https://BitriseAPI-xxx.repl.co/')
    .then(res => res.json())
    .then((res) => {
      console.log('Keep Alive');
    });
}
```

Why repl.co url hardcoded in node code?

**Comment by DamienBitrise** [comment]
Nice catch yes this is a workaround for Repl to keep the service alive. Repl shut down servers if not used for 10mins

If you run this on your own server and not on Repl this is not required.

**Comment by DamienBitrise** [comment]
I added this step to the Readme

https://github.com/DamienBitrise/bitrise-grafana-api/commit/d3d69b794dd26c47b595bda5547533d157ff368c

**Comment by azhurbilo** [comment]
> If you run this on your own server and not on Repl this is not required.

@DamienBitrise do I need explicitly delete this keepAlive() function if I run it on my own server?
want to be sure to prevent any security issue :)

**Comment by DamienBitrise** [comment]
No the keep alive is not required when running on your own server.

This code is provided as a guide to show what is possible using the Bitrise API.

Please feel free to fork and modify to meet your specific needs.
